WB-2008 transformation upon requested formats
opendigitaleducation/edifice-tiptap-transformer pull request #1
Opened 2023-09-18 08:15 UTC by mariusode

https://edifice-community.atlassian.net/browse/WB-2008

Content transformer API evolves to offer transformation toward a potentially extensible list of formats, specified in the request.
For now it enables to retrieve plain text content that can be used for content indexation

2023-09-18 11:41 UTC, juniorode requested changes

2023-09-18 11:41 UTC, juniorode commented on index.ts
> +    } else if (data.jsonContent != null) {
Là il faudrait aussi ajouter le compteur pour le _plain_

2023-09-18 11:41 UTC, juniorode commented on src/controllers/transformation-controller.ts
>    console.log(data)
C'est un vieux reliquat de debug que j'ai dû laisser. Est-ce que tu pourrais en profiter pour l'enlever stp ?

2023-09-18 11:42 UTC, juniorode commented
En plus des 2 commentaires, j'en aurais aussi ajouté un sur le `README.md` qui n'est plus à jour.

2023-09-18 11:53 UTC, juniorode commented on src/controllers/transformation-controller.ts
> +  if (data.htmlContent != null) {
J'ai un petit doute sur cette façon de faire parce qu'on ne se base sur le champ `requestedFormats` qu'a posteriori. Ce qui peut nous amener à des cas d'erreurs bizarres ou surprenant pour le client.
Par exemple :
- si un client nous envoie du json et du html dans la réponse mais demande de l'html alors on lui renvoie que le json
- si un client nous envoie du contenu non cohérent avec ce qu'il demande alors il ne reçoit pas d'erreur spécifique (un client qui enverrait de l'html et demanderait de l'html par exemple)

2023-09-18 15:24 UTC, mariusode commented on src/controllers/transformation-controller.ts
> +  if (data.htmlContent != null) {
En fait je me demandais : est-ce qu'un cas du genre "je fournis du contenu html et je demande du html" peut représenter un rattrapage dans la version du format du contenu riche ?

2023-09-18 15:27 UTC, juniorode commented on src/controllers/transformation-controller.ts
> +  if (data.htmlContent != null) {
Par exemple oui. Ou un nettoyage aussi.

2023-09-20 07:09 UTC, juniorode commented on index.ts
> -const port = process.env.PORT || 3000;
ça ça va casser le container par défaut. Si chez toi tu veux un autre port tu peux le changer dans le fichier `.env`

2023-09-20 07:12 UTC, juniorode requested changes

2023-09-20 07:12 UTC, juniorode commented on index.ts
>    console.log(`Example app listening on port ${port}`)
Rien à voir mais ça on pourrait le supprimer je pense

2023-09-20 07:12 UTC, juniorode commented on src/controllers/transformation-controller.ts
> +        plainTextContent = generateText(generateJSON(data.htmlContent, EXTENSIONS), EXTENSIONS);
Ici je pense qu'on pourrait réutiliser le json qui a été généré plus haut si possible

2023-09-20 08:08 UTC, mariusode commented on index.ts
> -const port = process.env.PORT || 3000;
ah oui bien vu, pas fait exprès

2023-09-20 09:37 UTC, mariusode commented on index.ts
>    console.log(`Example app listening on port ${port}`)
En fait j'ai l'impression que ça fait parti du minimum à renseigner pour exposer le port :
https://expressjs.com/fr/starter/hello-world.html

2023-09-20 09:39 UTC, mariusode commented on src/controllers/transformation-controller.ts
> +        plainTextContent = generateText(generateJSON(data.htmlContent, EXTENSIONS), EXTENSIONS);
j'ai légèrement changé l'implémentation pour que, dans le cas où il aurait déjà été généré, on se base sur le jsonContent pour générer le plainTextContent

2023-09-21 07:15 UTC, juniorode commented on index.ts
>    console.log(`Example app listening on port ${port}`)
`app.listen(port, () => {})` oui c'est le minimum. Le console .log est superflu. Mais c'est pas grave, on pourra l'enlever plus tard

2023-09-21 07:17 UTC, juniorode approved these changes

2023-09-21 07:17 UTC, merged